const freezeValues = values => Object.freeze([...values]);

const INTEGRATION_DOMAINS = freezeValues([
  'CUSTOMER',
  'BOOKING',
  'CLUB',
  'COMMERCE',
  'CATALOG',
  'INVENTORY',
  'FULFILMENT',
  'WORKFORCE',
  'COMMUNICATION'
]);

const CONNECTION_STATUSES = freezeValues([
  'PENDING',
  'CONNECTED',
  'DEGRADED',
  'REAUTH_REQUIRED',
  'DISABLED',
  'ERROR'
]);

const CAPABILITY_KINDS = freezeValues(['READ', 'WRITE']);
const CAPABILITY_AVAILABILITY_STATUSES = freezeValues(['AVAILABLE', 'DEGRADED', 'UNAVAILABLE']);
const INITIAL_BACKFILL_STATUSES = freezeValues(['NOT_STARTED', 'RUNNING', 'COMPLETE', 'FAILED']);
const SYNC_RUN_MODES = freezeValues(['BACKFILL', 'INCREMENTAL', 'RECONCILIATION', 'WEBHOOK_RECOVERY']);
const SYNC_RUN_STATUSES = freezeValues(['RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED']);
const EXTERNAL_RESOURCE_RESOLUTION_STATUSES = freezeValues(['UNRESOLVED', 'RESOLVED', 'AMBIGUOUS', 'IGNORED']);
const INTEGRATION_EVENT_CLASSES = freezeValues(['SOURCE', 'INTAKE', 'CANONICAL', 'DERIVED']);
const INGESTION_PURPOSES = freezeValues(['LIVE', 'HYDRATION', 'RECONCILIATION', 'MANUAL_REPLAY']);
const PROJECTION_ISSUE_STATUSES = freezeValues(['OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'IGNORED']);
const PROJECTION_ISSUE_SEVERITIES = freezeValues(['INFO', 'WARNING', 'ERROR', 'BLOCKING']);
const PROJECTION_ISSUE_TYPES = freezeValues([
  'CONNECTION_MAPPING_AMBIGUOUS',
  'CONNECTION_MAPPING_STALE',
  'IDENTITY_AMBIGUOUS',
  'LOCATION_UNMAPPED',
  'PRODUCT_UNMAPPED',
  'STATUS_UNMAPPED',
  'SOURCE_CONFLICT',
  'OUT_OF_ORDER',
  'SCHEMA_INVALID',
  'MISSING_REQUIRED_FIELD'
]);
const AUTHORITY_POLICY_STATUSES = freezeValues(['DRAFT', 'ACTIVE', 'RETIRED']);
const AUTHORITY_RESOLUTION_STRATEGIES = freezeValues(['SOURCE_PRIORITY', 'VINAGENT_OWNED']);
const AUTHORITY_SOURCE_ROLES = freezeValues(['PRIMARY', 'FALLBACK']);
const INTEGRATION_JOB_STATUSES = freezeValues(['PENDING', 'RUNNING', 'RETRY', 'SUCCEEDED', 'FAILED', 'CANCELLED']);
const CANONICAL_OUTBOX_STATUSES = freezeValues(['PENDING', 'DELIVERING', 'DELIVERED', 'RETRY', 'FAILED']);
const SYNC_STREAM_OPERATIONAL_STATUSES = freezeValues(['ACTIVE', 'PAUSED']);
const CANONICAL_RESOURCE_TYPES = freezeValues([
  'CUSTOMER',
  'BOOKING',
  'WINE_CLUB_MEMBERSHIP',
  'WINE_CLUB_ALLOCATION',
  'SALES_ORDER',
  'PRODUCT_VARIANT',
  'STOCK_LOCATION',
  'INVENTORY_POSITION',
  'INVENTORY_COMMITMENT',
  'SHIPMENT',
  'STAFF_IDENTITY',
  'MESSAGE',
  'WINERY_PRODUCT',
  'ROSTER_SHIFT'
]);
const OPERATIONAL_RESOURCE_ITEM_TYPES = freezeValues(['TASK', 'NOTICE', 'REQUEST', 'NOTE', 'PROJECT', 'CALENDAR_EVENT']);
const OPERATIONAL_RESOURCE_LINK_TYPES = freezeValues(['ABOUT', 'GENERATED_FOR', 'BLOCKS', 'RESOLVES', 'FOLLOW_UP_FOR']);
const LOCATION_AREA_RELATIONSHIP_TYPES = freezeValues(['PRIMARY_OPERATOR', 'SUPPORTS', 'STOCK_OWNER']);
const DOMAIN_ACTIVATION_STATUSES = freezeValues(['ACTIVE', 'DISABLED']);
const CONFIGURATION_AUTHORITY_STATUSES = freezeValues([
  'LEGACY_PRIMARY',
  'PREPARED',
  'CANONICAL_PRIMARY',
  'ROLLED_BACK'
]);
const CANONICAL_BOOKING_STATUSES = freezeValues([
  'TENTATIVE',
  'CONFIRMED',
  'CHECKED_IN',
  'IN_PROGRESS',
  'COMPLETED',
  'NO_SHOW',
  'CANCELLED',
  'UNKNOWN'
]);
const BOOKING_REQUIREMENT_KINDS = freezeValues([
  'EXPERIENCE',
  'ADD_ON',
  'DIETARY',
  'ACCESSIBILITY',
  'CELEBRATION',
  'SEATING',
  'TRANSPORT',
  'PRODUCT',
  'OTHER'
]);
const PROJECTION_QUALITY_STATES = freezeValues([
  'SOURCE_ASSERTED',
  'MANAGER_CONFIRMED',
  'DETERMINISTICALLY_DERIVED',
  'AI_INFERRED',
  'CONFLICTING',
  'UNKNOWN'
]);
const CUSTOMER_CONTACT_TYPES = freezeValues(['EMAIL', 'PHONE']);
const CUSTOMER_CONTACT_VERIFICATION_STATUSES = freezeValues(['UNKNOWN', 'UNVERIFIED', 'VERIFIED', 'INVALID']);
const CUSTOMER_CONSENT_CHANNELS = freezeValues(['EMAIL', 'SMS', 'PHONE', 'ANY']);
const CUSTOMER_CONSENT_STATES = freezeValues(['UNKNOWN', 'GRANTED', 'DENIED', 'REVOKED']);
const WINE_CLUB_MEMBERSHIP_STATUSES = freezeValues([
  'PENDING',
  'ACTIVE',
  'PAUSED',
  'PAYMENT_HOLD',
  'CANCELLING',
  'CANCELLED',
  'EXPIRED',
  'UNKNOWN'
]);
const WINE_CLUB_ALLOCATION_STATUSES = freezeValues([
  'PLANNED',
  'OPEN',
  'LOCKED',
  'CHARGED',
  'FULFILMENT_PENDING',
  'FULFILLED',
  'SKIPPED',
  'CANCELLED',
  'UNKNOWN'
]);
const ENTITY_RESOLUTION_STATUSES = freezeValues(['RESOLVED', 'UNRESOLVED', 'NOT_APPLICABLE']);
const SALES_ORDER_STATUSES = freezeValues([
  'DRAFT',
  'OPEN',
  'PLACED',
  'PAID',
  'PARTIALLY_FULFILLED',
  'FULFILLED',
  'CANCELLED',
  'PARTIALLY_REFUNDED',
  'REFUNDED',
  'UNKNOWN'
]);
const SALES_ORDER_CHANNELS = freezeValues([
  'POS',
  'ECOMMERCE',
  'WINE_CLUB',
  'CELLAR_DOOR',
  'PHONE',
  'MANUAL',
  'WHOLESALE',
  'OTHER',
  'UNKNOWN'
]);
const SALES_ORDER_LINE_TYPES = freezeValues(['PRODUCT', 'SHIPPING', 'FEE', 'DISCOUNT', 'TAX', 'OTHER']);
const PAYMENT_SUMMARY_STATUSES = freezeValues([
  'PENDING',
  'AUTHORIZED',
  'PARTIALLY_PAID',
  'PAID',
  'FAILED',
  'VOIDED',
  'PARTIALLY_REFUNDED',
  'REFUNDED',
  'CHARGEBACK',
  'NOT_REQUIRED',
  'UNKNOWN'
]);
const FULFILMENT_SUMMARY_STATUSES = freezeValues([
  'UNFULFILLED',
  'PARTIAL',
  'FULFILLED',
  'RETURNED',
  'CANCELLED',
  'NOT_REQUIRED',
  'UNKNOWN'
]);
const PAYMENT_SUMMARY_EVENT_TYPES = freezeValues([
  'AUTHORIZED',
  'CAPTURED',
  'FAILED',
  'VOIDED',
  'SETTLED',
  'REFUNDED',
  'CHARGEBACK',
  'ADJUSTED',
  'UNKNOWN'
]);
const PAYMENT_METHOD_CLASSES = freezeValues([
  'CARD',
  'CASH',
  'BANK_TRANSFER',
  'GIFT_CARD',
  'ACCOUNT',
  'OTHER',
  'UNKNOWN'
]);
const REFUND_SUMMARY_STATUSES = freezeValues(['PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'UNKNOWN']);
const BUSINESS_ENTITY_RELATIONSHIP_TYPES = freezeValues([
  'BOOKING_RESULTED_IN_ORDER',
  'POSSIBLE_SAME_CUSTOMER',
  'POSSIBLE_SAME_SALES_ORDER'
]);
const BUSINESS_ENTITY_LINK_DERIVATION_TYPES = freezeValues([
  'SOURCE_ASSERTED',
  'DETERMINISTIC',
  'AI_INFERRED',
  'MANAGER_CONFIRMED'
]);
const BUSINESS_ENTITY_LINK_CONFIRMATION_STATUSES = freezeValues([
  'UNREVIEWED',
  'CONFIRMED',
  'REJECTED',
  'INVALIDATED'
]);
const CUSTOMER_ROLLUP_RUN_STATUSES = freezeValues(['RUNNING', 'COMPLETE', 'FAILED']);
const CUSTOMER_ROLLUP_OVERLAP_STATUSES = freezeValues(['CLEAR', 'POSSIBLE_DUPLICATES']);
const CUSTOMER_ROLLUP_AUTHORITY_STATUSES = freezeValues(['SHADOW_UNVERIFIED', 'CANONICAL_ACTIVE']);
const INVENTORY_POSITION_QUALITY_STATES = freezeValues([
  'SOURCE_ASSERTED',
  'MANAGER_CONFIRMED',
  'CONFLICTING',
  'UNKNOWN'
]);
const INVENTORY_COMMITMENT_SOURCE_TYPES = freezeValues([
  'BOOKING',
  'WINE_CLUB_ALLOCATION',
  'SALES_ORDER',
  'INTERNAL_EVENT'
]);
const INVENTORY_COMMITMENT_STATUSES = freezeValues([
  'EXPECTED',
  'RESERVED',
  'CONSUMED',
  'RELEASED',
  'CANCELLED'
]);
const INVENTORY_COMMITMENT_DERIVATIONS = freezeValues([
  'SOURCE_ASSERTED',
  'DETERMINISTIC',
  'MANAGER_CONFIRMED'
]);
const INVENTORY_AVAILABILITY_STATUSES = freezeValues([
  'AVAILABLE',
  'SHORTAGE',
  'UNKNOWN',
  'STALE',
  'UNIT_MISMATCH',
  'SOURCE_CONFLICT'
]);
const INVENTORY_DEMAND_SOURCE_RECORD_TYPES = freezeValues([
  'BOOKING_REQUIREMENT',
  'WINE_CLUB_ALLOCATION_ITEM',
  'SALES_ORDER_LINE'
]);
const INVENTORY_DEMAND_MAPPING_STATUSES = freezeValues(['ACTIVE', 'DISABLED']);
const SHIPMENT_STATUSES = freezeValues([
  'LABEL_CREATED',
  'READY',
  'IN_TRANSIT',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'DELIVERY_EXCEPTION',
  'RETURN_IN_TRANSIT',
  'RETURNED',
  'CANCELLED',
  'UNKNOWN'
]);
const SHIPMENT_TRACKING_EVENT_CODES = freezeValues([
  'LABEL_CREATED',
  'PICKED_UP',
  'IN_TRANSIT',
  'ARRIVED_AT_FACILITY',
  'DEPARTED_FACILITY',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'DELIVERY_ATTEMPTED',
  'DELAYED',
  'EXCEPTION',
  'RETURN_IN_TRANSIT',
  'RETURNED',
  'CANCELLED',
  'UNKNOWN'
]);
const SHIPMENT_EXCEPTION_CATEGORIES = freezeValues([
  'NONE',
  'DELAYED',
  'ADDRESS_ISSUE',
  'RECIPIENT_UNAVAILABLE',
  'DAMAGED',
  'LOST',
  'CUSTOMS',
  'WEATHER',
  'CARRIER',
  'RETURN',
  'OTHER',
  'UNKNOWN'
]);
const STAFF_EMPLOYMENT_STATUSES = freezeValues([
  'ACTIVE',
  'INACTIVE',
  'ON_LEAVE',
  'TERMINATED',
  'UNRESOLVED',
  'UNKNOWN'
]);
const ROLE_SKILL_DEFINITION_KINDS = freezeValues(['ROLE', 'SKILL']);
const STAFF_ROLE_SKILL_STATUSES = freezeValues(['ACTIVE', 'EXPIRED', 'REVOKED']);
const ROSTER_SHIFT_STATUSES = freezeValues([
  'DRAFT',
  'SCHEDULED',
  'CONFIRMED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
  'UNKNOWN'
]);
const ROSTER_PUBLISHED_STATES = freezeValues(['DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'UNKNOWN']);
const STAFF_AVAILABILITY_TYPES = freezeValues([
  'AVAILABLE',
  'UNAVAILABLE',
  'LEAVE',
  'SICK_LEAVE',
  'TRAINING',
  'OTHER',
  'UNKNOWN'
]);
const STAFF_AVAILABILITY_STATUSES = freezeValues([
  'REQUESTED',
  'APPROVED',
  'DECLINED',
  'CANCELLED',
  'SOURCE_ASSERTED',
  'UNKNOWN'
]);
const WORKFORCE_DEMAND_SOURCE_RECORD_TYPES = freezeValues(['BOOKING_TYPE', 'BOOKING_REQUIREMENT']);
const WORKFORCE_DEMAND_MAPPING_STATUSES = freezeValues(['ACTIVE', 'DISABLED']);
const MESSAGE_DELIVERY_STATUSES = freezeValues([
  'RECEIVED',
  'QUEUED',
  'ACCEPTED',
  'SENT',
  'DELIVERED',
  'READ',
  'COMPLETED',
  'DEFERRED',
  'BOUNCED',
  'FAILED',
  'UNDELIVERABLE',
  'UNKNOWN'
]);
const MESSAGE_DELIVERY_FAILURE_CATEGORIES = freezeValues([
  'NONE',
  'PROVIDER_REJECTED',
  'ADDRESS_INVALID',
  'AUTHENTICATION',
  'RATE_LIMITED',
  'SPAM_BLOCKED',
  'EXPIRED',
  'OTHER',
  'UNKNOWN'
]);
const INTELLIGENCE_FACT_VALUE_TYPES = freezeValues(['BOOLEAN', 'NUMBER', 'STRING', 'DATE', 'JSON']);
const INTELLIGENCE_FACT_QUALITY_CLASSES = freezeValues([
  'OBSERVED_SOURCE',
  'CANONICAL_RESOLVED',
  'DETERMINISTIC_DERIVED',
  'AI_INFERRED',
  'MANAGER_CONFIRMED',
  'CONFLICTING',
  'UNKNOWN'
]);
const INTELLIGENCE_FACT_DERIVATION_TYPES = freezeValues([
  'SOURCE_ASSERTED',
  'DETERMINISTIC',
  'AI_INFERRED',
  'MANAGER_CONFIRMED'
]);
const INTELLIGENCE_FACT_SENSITIVITY_CLASSES = freezeValues([
  'INTERNAL',
  'CUSTOMER_RESTRICTED',
  'WORKFORCE_RESTRICTED'
]);
const INTELLIGENCE_FACT_RUN_STATUSES = freezeValues(['RUNNING', 'COMPLETE', 'FAILED']);

const includesRegistryValue = (registry, value) => registry.includes(String(value || '').trim().toUpperCase());

const assertRegistryValue = (registry, value, fieldName) => {
  const normalized = String(value || '').trim().toUpperCase();
  if (!registry.includes(normalized)) {
    const error = new Error(`${fieldName} is not supported`);
    error.code = 'UNSUPPORTED_REGISTRY_VALUE';
    throw error;
  }
  return normalized;
};

module.exports = {
  INTEGRATION_DOMAINS,
  CONNECTION_STATUSES,
  CAPABILITY_KINDS,
  CAPABILITY_AVAILABILITY_STATUSES,
  INITIAL_BACKFILL_STATUSES,
  SYNC_RUN_MODES,
  SYNC_RUN_STATUSES,
  EXTERNAL_RESOURCE_RESOLUTION_STATUSES,
  INTEGRATION_EVENT_CLASSES,
  INGESTION_PURPOSES,
  PROJECTION_ISSUE_STATUSES,
  PROJECTION_ISSUE_SEVERITIES,
  PROJECTION_ISSUE_TYPES,
  AUTHORITY_POLICY_STATUSES,
  AUTHORITY_RESOLUTION_STRATEGIES,
  AUTHORITY_SOURCE_ROLES,
  INTEGRATION_JOB_STATUSES,
  CANONICAL_OUTBOX_STATUSES,
  SYNC_STREAM_OPERATIONAL_STATUSES,
  CANONICAL_RESOURCE_TYPES,
  OPERATIONAL_RESOURCE_ITEM_TYPES,
  OPERATIONAL_RESOURCE_LINK_TYPES,
  LOCATION_AREA_RELATIONSHIP_TYPES,
  DOMAIN_ACTIVATION_STATUSES,
  CONFIGURATION_AUTHORITY_STATUSES,
  CANONICAL_BOOKING_STATUSES,
  BOOKING_REQUIREMENT_KINDS,
  PROJECTION_QUALITY_STATES,
  CUSTOMER_CONTACT_TYPES,
  CUSTOMER_CONTACT_VERIFICATION_STATUSES,
  CUSTOMER_CONSENT_CHANNELS,
  CUSTOMER_CONSENT_STATES,
  WINE_CLUB_MEMBERSHIP_STATUSES,
  WINE_CLUB_ALLOCATION_STATUSES,
  ENTITY_RESOLUTION_STATUSES,
  SALES_ORDER_STATUSES,
  SALES_ORDER_CHANNELS,
  SALES_ORDER_LINE_TYPES,
  PAYMENT_SUMMARY_STATUSES,
  FULFILMENT_SUMMARY_STATUSES,
  PAYMENT_SUMMARY_EVENT_TYPES,
  PAYMENT_METHOD_CLASSES,
  REFUND_SUMMARY_STATUSES,
  BUSINESS_ENTITY_RELATIONSHIP_TYPES,
  BUSINESS_ENTITY_LINK_DERIVATION_TYPES,
  BUSINESS_ENTITY_LINK_CONFIRMATION_STATUSES,
  CUSTOMER_ROLLUP_RUN_STATUSES,
  CUSTOMER_ROLLUP_OVERLAP_STATUSES,
  CUSTOMER_ROLLUP_AUTHORITY_STATUSES,
  INVENTORY_POSITION_QUALITY_STATES,
  INVENTORY_COMMITMENT_SOURCE_TYPES,
  INVENTORY_COMMITMENT_STATUSES,
  INVENTORY_COMMITMENT_DERIVATIONS,
  INVENTORY_AVAILABILITY_STATUSES,
  INVENTORY_DEMAND_SOURCE_RECORD_TYPES,
  INVENTORY_DEMAND_MAPPING_STATUSES,
  SHIPMENT_STATUSES,
  SHIPMENT_TRACKING_EVENT_CODES,
  SHIPMENT_EXCEPTION_CATEGORIES,
  STAFF_EMPLOYMENT_STATUSES,
  ROLE_SKILL_DEFINITION_KINDS,
  STAFF_ROLE_SKILL_STATUSES,
  ROSTER_SHIFT_STATUSES,
  ROSTER_PUBLISHED_STATES,
  STAFF_AVAILABILITY_TYPES,
  STAFF_AVAILABILITY_STATUSES,
  WORKFORCE_DEMAND_SOURCE_RECORD_TYPES,
  WORKFORCE_DEMAND_MAPPING_STATUSES,
  MESSAGE_DELIVERY_STATUSES,
  MESSAGE_DELIVERY_FAILURE_CATEGORIES,
  INTELLIGENCE_FACT_VALUE_TYPES,
  INTELLIGENCE_FACT_QUALITY_CLASSES,
  INTELLIGENCE_FACT_DERIVATION_TYPES,
  INTELLIGENCE_FACT_SENSITIVITY_CLASSES,
  INTELLIGENCE_FACT_RUN_STATUSES,
  includesRegistryValue,
  assertRegistryValue
};
