const { Op } = require('sequelize');
const { Notification, Task, TaskStep } = require('../models');
const { pickTaskOutcomeSnapshot } = require('../utils/taskOutcome');
const auditService = require('./audit.service');
const { findManagerUserId } = require('./taskAssignment.service');
const {
  AUTO_FOLLOW_UP_TYPES,
  buildFollowUpPlan,
  buildFollowUpSteps,
  buildManagedFollowUpPayload,
  isAutoGeneratedFollowUpTask
} = require('./taskFollowUpPlan.service');
const { diffOutcomeSnapshots } = require('./taskWorkflowPolicy.service');
const { safeRecordUsageEvent } = require('./usageTracking.service');
const { METRICS } = require('./usageMetricCatalog');
const {
  createTaskSteps,
  getOrderedTaskSteps,
  syncTaskWorkflow
} = require('./taskWorkflow.service');

async function resolveFollowUpAssignee(task, plan, transaction) {
  if (plan.automationType === AUTO_FOLLOW_UP_TYPES.ESCALATION_REVIEW) {
    return await findManagerUserId(task.wineryId, transaction) || task.assigneeId || task.createdBy || null;
  }

  return task.assigneeId || task.createdBy || await findManagerUserId(task.wineryId, transaction) || null;
}

async function getManagedFollowUpTasks(parentTaskId, transaction) {
  const childTasks = await Task.findAll({
    where: { parentTaskId },
    order: [['createdAt', 'DESC'], ['id', 'DESC']],
    transaction
  });

  return childTasks.filter(child => isAutoGeneratedFollowUpTask(child));
}

async function notifyFollowUpAssignee({ assigneeId, followUpTask, parentTask, plan, transaction }) {
  if (!assigneeId) return;

  await Notification.create({
    userId: assigneeId,
    type: 'SYSTEM',
    message: plan.reminderMessage,
    data: {
      taskId: followUpTask.id,
      parentTaskId: parentTask.id,
      automationType: plan.automationType
    }
  }, { transaction });
}

async function createManagedFollowUpTask({ parentTask, plan, userId, transaction }) {
  const assigneeId = await resolveFollowUpAssignee(parentTask, plan, transaction);
  const payload = buildManagedFollowUpPayload(parentTask, plan, userId);

  const followUpTask = await Task.create({
    wineryId: parentTask.wineryId,
    category: plan.category,
    subType: plan.subType,
    customerType: parentTask.customerType,
    type: plan.subType,
    status: 'PENDING',
    priority: plan.priority,
    sentiment: parentTask.sentiment || 'NEUTRAL',
    workflowState: 'NOT_STARTED',
    waitingOn: 'NONE',
    payload,
    memberId: parentTask.memberId || null,
    suggestedChannel: 'none',
    dueAt: plan.dueAt,
    createdBy: userId || null,
    updatedBy: userId || null,
    assigneeId,
    parentTaskId: parentTask.id
  }, { transaction });

  await safeRecordUsageEvent({
    wineryId: parentTask.wineryId,
    actorUserId: userId,
    metricKey: METRICS.TASK_CREATED,
    quantity: 1,
    occurredAt: followUpTask.createdAt || new Date(),
    sourceType: 'task',
    sourceId: followUpTask.id,
    idempotencyKey: `task:${followUpTask.id}:created`,
    dimensions: {
      source: 'follow_up_automation',
      category: followUpTask.category,
      automation: 'true'
    },
    transaction
  });
  await safeRecordUsageEvent({
    wineryId: parentTask.wineryId,
    actorUserId: userId,
    metricKey: METRICS.AUTOMATION_EXECUTED,
    quantity: 1,
    occurredAt: followUpTask.createdAt || new Date(),
    sourceType: 'task',
    sourceId: followUpTask.id,
    idempotencyKey: `automation:${followUpTask.id}:created`,
    dimensions: { automationType: plan.automationType, result: 'success' },
    transaction
  });

  await auditService.logTaskAction({
    transaction,
    taskId: followUpTask.id,
    userId,
    actionType: 'CREATED',
    details: {
      source: 'follow_up_automation',
      automationType: plan.automationType,
      parentTaskId: parentTask.id
    }
  });

  await createTaskSteps({
    taskId: followUpTask.id,
    steps: buildFollowUpSteps(parentTask, plan, assigneeId),
    fallbackOwnerUserId: assigneeId,
    userId,
    transaction
  });

  await syncTaskWorkflow(followUpTask, transaction);

  await auditService.logTaskAction({
    transaction,
    taskId: parentTask.id,
    userId,
    actionType: 'LINKED_TASK',
    details: {
      parentTaskId: parentTask.id,
      childTaskId: followUpTask.id,
      relationship: 'AUTO_FOLLOW_UP',
      automationType: plan.automationType,
      automationAction: 'created'
    }
  });

  await notifyFollowUpAssignee({
    assigneeId,
    followUpTask,
    parentTask,
    plan,
    transaction
  });

  return followUpTask;
}

async function updateManagedFollowUpTask({ managedTask, parentTask, plan, userId, transaction }) {
  const assigneeId = await resolveFollowUpAssignee(parentTask, plan, transaction);
  const nextPayload = buildManagedFollowUpPayload(parentTask, plan, userId);
  const changes = {};
  const oldValues = {};

  const setFollowUpField = (field, value) => {
    const currentValue = managedTask[field];
    const currentSerialized = currentValue instanceof Date ? currentValue.toISOString() : JSON.stringify(currentValue);
    const nextSerialized = value instanceof Date ? value.toISOString() : JSON.stringify(value);
    if (currentSerialized !== nextSerialized) {
      changes[field] = value;
      oldValues[field] = currentValue;
      managedTask[field] = value;
    }
  };

  setFollowUpField('category', plan.category);
  setFollowUpField('subType', plan.subType);
  setFollowUpField('type', plan.subType);
  setFollowUpField('priority', plan.priority);
  setFollowUpField('dueAt', plan.dueAt);
  setFollowUpField('assigneeId', assigneeId);
  setFollowUpField('memberId', parentTask.memberId || null);

  const currentPayloadSerialized = JSON.stringify(managedTask.payload || null);
  const nextPayloadSerialized = JSON.stringify(nextPayload);
  if (currentPayloadSerialized !== nextPayloadSerialized) {
    changes.payload = nextPayload;
    oldValues.payload = managedTask.payload;
    managedTask.payload = nextPayload;
    managedTask.changed('payload', true);
  }

  if (Object.keys(changes).length > 0) {
    managedTask.updatedBy = userId || null;
    await managedTask.save({ transaction });

    await auditService.logTaskAction({
      transaction,
      taskId: managedTask.id,
      userId,
      actionType: 'MANUAL_UPDATE',
      details: {
        source: 'follow_up_automation',
        automationType: plan.automationType,
        changes,
        oldValues
      }
    });

    await auditService.logTaskAction({
      transaction,
      taskId: parentTask.id,
      userId,
      actionType: 'LINKED_TASK',
      details: {
        parentTaskId: parentTask.id,
        childTaskId: managedTask.id,
        relationship: 'AUTO_FOLLOW_UP',
        automationType: plan.automationType,
        automationAction: 'updated'
      }
    });
  }

  const childSteps = await getOrderedTaskSteps(managedTask.id, transaction);
  if (childSteps.length === 0) {
    await createTaskSteps({
      taskId: managedTask.id,
      steps: buildFollowUpSteps(parentTask, plan, assigneeId),
      fallbackOwnerUserId: assigneeId,
      userId,
      transaction
    });
  }

  await syncTaskWorkflow(managedTask, transaction);
  return managedTask;
}

async function cancelManagedFollowUpTask({ managedTask, parentTask, userId, reason, transaction }) {
  if (!managedTask || managedTask.status !== 'PENDING') {
    return managedTask;
  }

  const previousStatus = managedTask.status;
  const previousOutcome = pickTaskOutcomeSnapshot(managedTask);

  managedTask.status = 'REJECTED';
  managedTask.workflowState = 'CANCELLED';
  managedTask.waitingOn = 'NONE';
  managedTask.nextStepSummary = null;
  managedTask.blockedReason = null;
  managedTask.updatedBy = userId || null;
  managedTask.resolvedAs = 'NO_ACTION';
  managedTask.resolutionType = 'ALREADY_RESOLVED';
  managedTask.customerOutcome = 'NO_CHANGE';
  managedTask.resolutionSummary = reason;
  managedTask.followUpRequired = false;
  managedTask.followUpDueAt = null;
  managedTask.followUpSummary = null;
  managedTask.resolvedAt = new Date();

  await managedTask.save({ transaction });

  await TaskStep.update({
    status: 'CANCELLED',
    updatedBy: userId || null
  }, {
    where: {
      taskId: managedTask.id,
      status: {
        [Op.notIn]: ['COMPLETED', 'SKIPPED', 'CANCELLED']
      }
    },
    transaction
  });

  await auditService.logTaskAction({
    transaction,
    taskId: managedTask.id,
    userId,
    actionType: 'REJECTED',
    details: {
      source: 'follow_up_automation',
      reason,
      changes: {
        status: 'REJECTED'
      },
      oldValues: {
        status: previousStatus
      }
    }
  });

  const outcomeDiff = diffOutcomeSnapshots(previousOutcome, pickTaskOutcomeSnapshot(managedTask));
  if (Object.keys(outcomeDiff.changes).length > 0) {
    await auditService.logTaskAction({
      transaction,
      taskId: managedTask.id,
      userId,
      actionType: 'OUTCOME_RECORDED',
      details: outcomeDiff
    });
  }

  await auditService.logTaskAction({
    transaction,
    taskId: parentTask.id,
    userId,
    actionType: 'LINKED_TASK',
    details: {
      parentTaskId: parentTask.id,
      childTaskId: managedTask.id,
      relationship: 'AUTO_FOLLOW_UP',
      automationType: managedTask.payload?.followUpAutomation?.automationType || null,
      automationAction: 'cancelled',
      reason
    }
  });

  await syncTaskWorkflow(managedTask, transaction);
  return managedTask;
}

async function syncFollowUpAutomation(task, userId, transaction) {
  if (!task || isAutoGeneratedFollowUpTask(task)) {
    return null;
  }

  const managedTasks = await getManagedFollowUpTasks(task.id, transaction);
  const activeManagedTask = managedTasks.find(childTask => childTask.status === 'PENDING') || null;
  const desiredPlan = buildFollowUpPlan(task);

  if (!desiredPlan) {
    if (activeManagedTask) {
      await cancelManagedFollowUpTask({
        managedTask: activeManagedTask,
        parentTask: task,
        userId,
        reason: `Follow-up automation cleared because task #${task.id} no longer requires an active follow-up.`,
        transaction
      });
    }
    return null;
  }

  if (
    activeManagedTask
    && activeManagedTask.payload?.followUpAutomation?.automationType === desiredPlan.automationType
  ) {
    return updateManagedFollowUpTask({
      managedTask: activeManagedTask,
      parentTask: task,
      plan: desiredPlan,
      userId,
      transaction
    });
  }

  if (activeManagedTask) {
    await cancelManagedFollowUpTask({
      managedTask: activeManagedTask,
      parentTask: task,
      userId,
      reason: `Follow-up automation changed for task #${task.id}; replacing the previous automated follow-up.`,
      transaction
    });
  }

  return createManagedFollowUpTask({
    parentTask: task,
    plan: desiredPlan,
    userId,
    transaction
  });
}

module.exports = {
  syncFollowUpAutomation
};
