const AUTO_FOLLOW_UP_TYPES = {
  EXPLICIT: 'EXPLICIT_FOLLOW_UP',
  CUSTOMER_CALLBACK: 'CUSTOMER_NO_RESPONSE_CALLBACK',
  ESCALATION_REVIEW: 'ESCALATION_REVIEW'
};

function isAutoGeneratedFollowUpTask(task) {
  return Boolean(task?.payload?.followUpAutomation?.isAutoGenerated);
}

function addHours(date, hours) {
  return new Date(date.getTime() + (hours * 60 * 60 * 1000));
}

function addDays(date, days) {
  return addHours(date, days * 24);
}

function formatTaskLabel(task) {
  return String(task?.subType || task?.category || 'TASK')
    .replace(/_/g, ' ')
    .toLowerCase();
}

function buildManagedFollowUpPayload(parentTask, plan, userId) {
  return {
    summary: plan.summary,
    followUpAutomation: {
      isAutoGenerated: true,
      sourceTaskId: parentTask.id,
      automationType: plan.automationType,
      generatedAt: new Date().toISOString(),
      generatedByUserId: userId || null
    },
    parentOutcome: {
      resolvedAs: parentTask.resolvedAs || null,
      resolutionType: parentTask.resolutionType || null,
      customerOutcome: parentTask.customerOutcome || null,
      resolutionSummary: parentTask.resolutionSummary || null,
      followUpRequired: Boolean(parentTask.followUpRequired),
      followUpDueAt: parentTask.followUpDueAt || null,
      followUpSummary: parentTask.followUpSummary || null,
      resolvedAt: parentTask.resolvedAt || null
    }
  };
}

function buildFollowUpSteps(parentTask, plan, ownerUserId) {
  const shared = {
    ownerUserId,
    dueAt: plan.dueAt,
    metadata: { automationType: plan.automationType, sourceTaskId: parentTask.id }
  };
  const steps = [{
    ...shared,
    title: 'Review the original case',
    description: `Review task #${parentTask.id} and confirm the next follow-up action.`,
    stepType: 'INTERNAL',
    waitingOn: 'STAFF',
    sortOrder: 0
  }];

  if (plan.automationType === AUTO_FOLLOW_UP_TYPES.CUSTOMER_CALLBACK) {
    steps.push({
      ...shared,
      title: 'Attempt customer callback',
      description: 'Reach back out to the customer and record whether they responded or the case can now be closed.',
      stepType: 'CUSTOMER_MESSAGE',
      waitingOn: 'STAFF',
      sortOrder: 1
    });
  } else if (plan.automationType === AUTO_FOLLOW_UP_TYPES.ESCALATION_REVIEW) {
    steps.push({
      ...shared,
      title: 'Confirm escalation owner',
      description: 'Ensure the escalation has a clear owner and next action before the case goes cold.',
      stepType: 'APPROVAL',
      waitingOn: 'MANAGER',
      sortOrder: 1
    });
  } else {
    steps.push({
      ...shared,
      title: 'Complete the follow-up',
      description: plan.summary,
      stepType: 'FOLLOW_UP',
      waitingOn: 'STAFF',
      sortOrder: 1
    });
  }

  return steps;
}

function buildFollowUpPlan(task) {
  if (!task || task.status === 'PENDING' || isAutoGeneratedFollowUpTask(task)) return null;

  const anchorDate = task.resolvedAt ? new Date(task.resolvedAt) : new Date();
  const taskLabel = formatTaskLabel(task);
  const isExternalTask = task.payload?.manualIntake?.taskOrigin === 'EXTERNAL';
  const subtype = task.subType || task.category || 'TASK';

  if (task.followUpRequired) {
    return {
      automationType: AUTO_FOLLOW_UP_TYPES.EXPLICIT,
      title: `Follow up on ${taskLabel}`,
      category: task.category || 'GENERAL',
      subType: `${subtype}_FOLLOW_UP`,
      priority: task.priority === 'high' ? 'high' : 'normal',
      dueAt: task.followUpDueAt ? new Date(task.followUpDueAt) : addDays(anchorDate, 1),
      summary: task.followUpSummary || `Follow up on task #${task.id} after closure and confirm the next outcome.`,
      reminderMessage: `Automated follow-up task created from task #${task.id}.`
    };
  }

  if (isExternalTask && task.resolutionType === 'CUSTOMER_NO_RESPONSE') {
    return {
      automationType: AUTO_FOLLOW_UP_TYPES.CUSTOMER_CALLBACK,
      title: `Retry contact for ${taskLabel}`,
      category: task.category || 'GENERAL',
      subType: `${subtype}_CALLBACK`,
      priority: 'normal',
      dueAt: addDays(anchorDate, 2),
      summary: `Customer did not respond on task #${task.id}. Retry contact and confirm whether the case can now be closed.`,
      reminderMessage: `Customer callback follow-up created from task #${task.id}.`
    };
  }

  if (task.resolvedAs === 'ESCALATED' || ['INTERNAL_ESCALATION', 'EXTERNAL_ESCALATION'].includes(task.resolutionType)) {
    return {
      automationType: AUTO_FOLLOW_UP_TYPES.ESCALATION_REVIEW,
      title: `Review escalated ${taskLabel}`,
      category: task.category || 'GENERAL',
      subType: `${subtype}_ESCALATION_REVIEW`,
      priority: 'high',
      dueAt: addHours(anchorDate, 24),
      summary: `Review the escalated case from task #${task.id} and confirm the next owner or external dependency.`,
      reminderMessage: `Escalation review follow-up created from task #${task.id}.`
    };
  }

  return null;
}

module.exports = {
  AUTO_FOLLOW_UP_TYPES,
  buildFollowUpPlan,
  buildFollowUpSteps,
  buildManagedFollowUpPayload,
  isAutoGeneratedFollowUpTask
};
