import type { CalendarEvent } from './calendarApi';
import type { JsonObject, Pagination } from './coreTypes';
import type { Notice } from './noticeTypes';
import type { AreaScope, OperationalArea } from './operationalAreaTypes';

export type TaskOrigin = 'INTERNAL' | 'EXTERNAL';
export type InboundMethod = 'internal' | 'email' | 'phone' | 'sms' | 'in_person' | 'other';
export type SuggestedChannel = 'sms' | 'email' | 'voice' | 'none';

export interface IdentitySuggestedCandidate {
    memberId: number;
    label: string;
    confidence: string;
    reason: string;
    score?: number;
    email?: string | null;
    phone?: string | null;
}

export interface ManualTaskIntake {
    requesterName?: string | null;
    requesterEmail?: string | null;
    requesterPhone?: string | null;
    inboundMethod?: InboundMethod | string | null;
    identityResolutionStatus?: string | null;
    identityConfidence?: string | null;
    memberMatchReason?: string | null;
    suggestedMemberReason?: string | null;
    suggestedCandidates?: IdentitySuggestedCandidate[];
    taskOrigin?: TaskOrigin | string | null;
    originalText?: string | null;
    [key: string]: unknown;
}

export interface FollowUpAutomation {
    automationType?: string | null;
    isAutoGenerated?: boolean;
    [key: string]: unknown;
}

export interface TaskPayload {
    summary?: string | null;
    title?: string | null;
    originalText?: string | null;
    note?: string | null;
    manualIntake?: ManualTaskIntake | null;
    followUpAutomation?: FollowUpAutomation | null;
    [key: string]: unknown;
}

export interface TaskActionDetails {
    changes?: Record<string, unknown>;
    oldValues?: Record<string, unknown>;
    blockedReason?: string | null;
    channel?: string | null;
    entityType?: string | null;
    filename?: string | null;
    isPrivate?: boolean;
    kind?: string | null;
    memberId?: number | null;
    note?: string | null;
    operation?: string | null;
    provider?: string | null;
    referenceCode?: string | null;
    status?: string | null;
    summary?: string | null;
    tagsAdded?: string[];
    target?: string | null;
    title?: string | null;
    to?: string | null;
    [key: string]: unknown;
}

export interface TaskStepMetadata {
    assignmentTargetRole?: string | null;
    reason?: string | null;
    [key: string]: unknown;
}

export interface Task {
    id: number;
    category: string;
    subType: string;
    customerType: string;
    type: string;
    status: string;
    workflowState?: string;
    waitingOn?: string;
    nextStepSummary?: string;
    blockedReason?: string;
    sentiment: string;
    priority: string;
    payload: TaskPayload;
    createdAt: string;
    dueAt?: string | null;
    deadlineState?: 'NONE' | 'SCHEDULED' | 'DUE_SOON' | 'OVERDUE';
    isOverdue?: boolean;
    isDueSoon?: boolean;
    hoursUntilDue?: number | null;
    overdueHours?: number | null;
    deadlineSortRank?: number;
    effectiveUrgency?: 'normal' | 'due_soon' | 'overdue';
    resolvedAs?: string | null;
    resolutionType?: string | null;
    customerOutcome?: string | null;
    resolutionSummary?: string | null;
    followUpRequired?: boolean;
    followUpDueAt?: string | null;
    followUpSummary?: string | null;
    resolvedAt?: string | null;
    notes?: string;
    assigneeId?: number;
    areaScope?: AreaScope;
    primaryAreaId?: number | null;
    linkedAreaIds?: number[];
    OperationalAreas?: OperationalArea[];
    parentTaskId?: number;
    suggestedReplyBody?: string;
    suggestedChannel?: string;
    suggestedReplySubject?: string;
    suggestedAction?: string;
    suggestedRecipientEmail?: string;
    suggestedCc?: string;
    memberId?: number;
    messageId?: number;
    Member?: { id: number; firstName: string; lastName: string; email?: string; phone?: string };
    Assignee?: { id: number; displayName: string; email?: string; role?: string };
    Creator?: { id: number; displayName: string; role?: string };
    ParentTask?: {
        id: number; category?: string | null; subType?: string | null; status: string;
        resolvedAs?: string | null; resolutionType?: string | null; customerOutcome?: string | null; resolvedAt?: string | null;
    };
    Message?: TaskMessage;
    Messages?: TaskMessage[];
    TaskSteps?: TaskStep[];
    TaskActions?: TaskAction[];
    SubTasks?: Task[];
    LinkedNotices?: Notice[];
    CalendarEvents?: CalendarEvent[];
    regenerateSuggestedReply?: boolean;
}

export interface TaskListResponse {
    tasks: Task[];
    pagination: Pagination;
}

export interface TaskQueueSummary {
    matching: number;
    highPriority: number;
    waiting: number;
    blocked: number;
    unassigned: number;
    overdue: number;
    dueSoon: number;
    identityReview: number;
    followUps: number;
}

export interface TaskMessage {
    id: number;
    source: string;
    direction: string;
    subject?: string | null;
    body?: string | null;
    receivedAt?: string | null;
    createdAt: string;
    rawPayload?: JsonObject | null;
}

export interface TaskAction {
    id: number;
    actionType: string;
    details?: TaskActionDetails;
    createdAt: string;
    userId?: number;
    User?: { id: number; displayName: string; role?: string; updatedAt: string };
}

export interface TaskStep {
    id: number;
    taskId: number;
    title: string;
    description?: string | null;
    stepType: string;
    status: string;
    waitingOn: string;
    sortOrder: number;
    ownerUserId?: number | null;
    dueAt?: string | null;
    blockedReason?: string | null;
    completionNotes?: string | null;
    suggestedReplyBody?: string | null;
    suggestedReplySubject?: string | null;
    suggestedChannel?: string | null;
    suggestedAction?: string | null;
    suggestedRecipientEmail?: string | null;
    suggestedCc?: string | null;
    suggestionStatus?: string | null;
    suggestionGeneratedAt?: string | null;
    suggestionError?: string | null;
    completedAt?: string | null;
    metadata?: TaskStepMetadata;
    Owner?: { id: number; displayName: string; email?: string; role?: string };
}

export interface TaskStepInput {
    title: string;
    description?: string | null;
    stepType?: string;
    status?: string;
    waitingOn?: string;
    sortOrder?: number;
    ownerUserId?: number | null;
    dueAt?: string | null;
    blockedReason?: string | null;
    completionNotes?: string | null;
    suggestedReplyBody?: string | null;
    suggestedReplySubject?: string | null;
    suggestedChannel?: string | null;
    suggestedAction?: string | null;
    suggestedRecipientEmail?: string | null;
    suggestedCc?: string | null;
    suggestionStatus?: string | null;
    suggestionGeneratedAt?: string | null;
    suggestionError?: string | null;
    metadata?: TaskStepMetadata;
}

export interface TaskStepActionSuggestionInput {
    suggestedReplyBody?: string | null;
    suggestedReplySubject?: string | null;
    suggestedChannel?: string | null;
    suggestedAction?: string | null;
    suggestedRecipientEmail?: string | null;
    suggestedCc?: string | null;
    completeStep?: boolean;
    completionNotes?: string | null;
}

export interface TaskFilters {
    status?: string;
    category?: string;
    priority?: string;
    sentiment?: string;
    assigneeId?: string | number;
    createdById?: string | number;
    actionedById?: string | number;
    areaId?: string | number;
    search?: string;
    sortBy?: string;
    dateFrom?: string;
    dateTo?: string;
    showOnlyFlagged?: boolean;
    mentionedMe?: boolean;
    deadlineState?: string;
    page?: number;
    pageSize?: number;
}

export interface AutoclassifyResponse {
    category: string;
    subType: string;
    priority: string;
    sentiment: string;
    payload: TaskPayload;
    suggestedTitle: string;
    suggestedReplyBody?: string;
    suggestedChannel?: string;
    suggestedReplySubject?: string;
    suggestedAction?: string;
    suggestedAssigneeId?: number;
    suggestedRecipientEmail?: string;
    suggestedCc?: string;
    suggestedSteps?: TaskStepInput[];
    suggestedMember?: { id: number; firstName: string; lastName: string; email?: string; phone?: string };
}
