const {
  AUTO_FOLLOW_UP_TYPES,
  buildFollowUpPlan,
  buildFollowUpSteps,
  buildManagedFollowUpPayload,
  isAutoGeneratedFollowUpTask
} = require('../../services/taskFollowUpPlan.service');

describe('taskFollowUpPlan service', () => {
  const closedTask = {
    id: 42,
    status: 'ACTIONED',
    category: 'BOOKING',
    subType: 'BOOKING_CHANGE',
    priority: 'normal',
    resolvedAt: '2026-07-11T00:00:00.000Z',
    payload: { manualIntake: { taskOrigin: 'EXTERNAL' } }
  };

  test('builds an explicit follow-up plan from the recorded outcome', () => {
    const plan = buildFollowUpPlan({
      ...closedTask,
      followUpRequired: true,
      followUpDueAt: '2026-07-15T01:00:00.000Z',
      followUpSummary: 'Confirm the revised booking.'
    });

    expect(plan).toMatchObject({
      automationType: AUTO_FOLLOW_UP_TYPES.EXPLICIT,
      subType: 'BOOKING_CHANGE_FOLLOW_UP',
      summary: 'Confirm the revised booking.'
    });
    expect(plan.dueAt.toISOString()).toBe('2026-07-15T01:00:00.000Z');
  });

  test('builds customer callback and escalation plans only for eligible closed tasks', () => {
    expect(buildFollowUpPlan({ ...closedTask, resolutionType: 'CUSTOMER_NO_RESPONSE' })).toMatchObject({
      automationType: AUTO_FOLLOW_UP_TYPES.CUSTOMER_CALLBACK,
      priority: 'normal'
    });
    expect(buildFollowUpPlan({ ...closedTask, resolvedAs: 'ESCALATED' })).toMatchObject({
      automationType: AUTO_FOLLOW_UP_TYPES.ESCALATION_REVIEW,
      priority: 'high'
    });
    expect(buildFollowUpPlan({ ...closedTask, status: 'PENDING' })).toBeNull();
    expect(buildFollowUpPlan({
      ...closedTask,
      payload: { followUpAutomation: { isAutoGenerated: true } }
    })).toBeNull();
  });

  test('creates deterministic workflow steps and audit payload metadata', () => {
    const plan = buildFollowUpPlan({ ...closedTask, resolutionType: 'CUSTOMER_NO_RESPONSE' });
    const steps = buildFollowUpSteps(closedTask, plan, 7);
    const payload = buildManagedFollowUpPayload(closedTask, plan, 9);

    expect(steps).toHaveLength(2);
    expect(steps[0]).toMatchObject({ ownerUserId: 7, sortOrder: 0, stepType: 'INTERNAL' });
    expect(steps[1]).toMatchObject({ ownerUserId: 7, sortOrder: 1, stepType: 'CUSTOMER_MESSAGE' });
    expect(payload.followUpAutomation).toMatchObject({
      isAutoGenerated: true,
      sourceTaskId: 42,
      generatedByUserId: 9
    });
    expect(isAutoGeneratedFollowUpTask({ payload })).toBe(true);
  });
});
